steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--platform=linux/amd64'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fashioncloset-server:latest'
      - '.'
images:
  - 'asia-northeast3-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/fashioncloset-server:latest'
